### ISSUE TITLE
Saving removes a story's labels

### ISSUE THREAD

**Issue by wefarrell** [dashofcode/tracker_api#110]
Steps to reproduce:
1. Create a story with a label
2. Load the story with tracker api
3. Save the story without modifying any of the attributes
--> Notice that the label is no longer present

**Comment by forest** [comment]
This is fixed here https://github.com/dashofcode/tracker_api/issues/104 and released in v1.7.1.

**Comment by g5codyswartz** [comment]
@forest I am also experiencing this on v1.7.1 currently still.

**Comment by g5codyswartz** [comment]
Here's the quick and dirty code I'm using
https://github.com/ctsstc/pivotal-tracker-story-sorter/blob/master/main.rb

I was going to verify it still occurs after removing the sorting section.

**Comment by forest** [comment]
I'm able to reproduce, but still diagnosing.

**Comment by g5codyswartz** [comment]
@forest Thanks for looking into it, I've been meaning to check into it myself, but haven't had much time yet.

**Comment by forest** [comment]
@g5codyswartz @wefarrell can you see if #112 fixes the issue you are seeing? Thanks.

**Comment by g5codyswartz** [comment]
@forest I added this to my `gemfile` ran bundler and it's still removing labels for me

`gem 'tracker_api', git: 'https://github.com/dashofcode/tracker_api.git', branch: 'no-delete-labels-on-save'`

**Comment by forest** [comment]
@g5codyswartz I downloaded your project, did a clean bundle install, and run it. I didn't see any labels removed. I even stepped through the code and verified the only attribute being sent in the update call is `after_id`.

https://github.com/dashofcode/tracker_api/blob/master/lib/tracker_api/endpoints/story.rb#L31
```
params.to_json
"{\"after_id\":66728272}"
```

**Comment by g5codyswartz** [comment]
@forest It looks to be working, thanks!

**Comment by forest** [comment]
Awesome. I'll push a new release later today or this weekend.

**Comment by ctsstc** [comment]
Much appreciated
